import { useCallback, useEffect, useRef, useState } from "react";
import {
  BookOpenText,
  Cable,
  CircleAlert,
  FlaskConical,
  LayoutDashboard,
  LoaderCircle,
  LogOut,
  Menu,
  ScrollText,
  Users,
  X,
} from "lucide-react";
import type { App } from "@unicas/admin-client";
import { api } from "../api.js";
import { navigate } from "../router.js";
import { formatErrorSafe } from "./view-helpers.js";
import { PageHeading } from "../components/page-heading.js";
import { AppOverviewView } from "./stack-overview.js";
import { MembersView } from "./members.js";
import { IssuerView } from "./issuer.js";
import { ControlAuditView } from "./control-audit.js";
import { UsageView } from "./usage.js";
import { PlaygroundView } from "./file-playground.js";

const TABS = [
  { id: "overview", label: "Overview", icon: <LayoutDashboard size={15} /> },
  { id: "playground", label: "Playground", icon: <FlaskConical size={15} /> },
  { id: "members", label: "Members", icon: <Users size={15} /> },
  { id: "change-log", label: "Change Log", icon: <ScrollText size={15} /> },
] as const;

const TAB_GUIDES = {
  overview: {
    title: "App identity",
    summary: "An App is UniCAS's top-level trust, administration, and storage namespace. It isolates issuer trust, Spaces, audit history, and stored CAS objects from every other App.",
    concepts: [
      { term: "App ID", detail: "An immutable opaque identifier generated by UniCAS and used in App and Space routes." },
      { term: "OAuth issuer", detail: "The authorization server that signs short-lived Space capabilities. UniCAS discovers its metadata and signing keys." },
      { term: "Usage", detail: "Space storage accounting remains isolated from the admin session and requires an explicit delegated capability." },
    ],
  },
  members: {
    title: "App administrators",
    summary: "Members administer this App through immutable Principal identity. Space capabilities and admin sessions are separate authentication planes.",
    concepts: [
      { term: "Principal", detail: "Membership binds the provider issuer and immutable subject; Profile email is display-only." },
      { term: "Equal access", detail: "All members currently have the same App-administrator permissions." },
      { term: "Transfer", detail: "Invite the replacement first, then remove the previous member. UniCAS will not allow removal of the final member." },
    ],
  },
  playground: {
    title: "Personal Space Playground",
    summary: "The managed issuer grants each App member a short-lived capability for an isolated development Space.",
    concepts: [
      { term: "Member access", detail: "Only current App members can issue managed capabilities." },
      { term: "Isolation", detail: "Each member maps to a stable personal Space without exposing the Principal in its Space ID." },
      { term: "Production", detail: "When the App switches to an external issuer, that issuer owns Space identity and authorization." },
    ],
  },
  "change-log": {
    title: "Change Log",
    summary: "This append-only log records administrative mutations to App configuration and membership.",
    concepts: [
      { term: "Actor", detail: "The immutable Principal that performed the operation." },
      { term: "Target", detail: "The App resource changed by the operation, with a request ID when available." },
      { term: "Scope", detail: "This log tracks App administration. Space data-plane debugging uses a separate workflow." },
    ],
  },
} as const;

export function AppView({ appId, onAppChange, onOpenMcpConfiguration, onLogout }: {
  appId: string;
  onAppChange?: (app: App | null) => void;
  onOpenMcpConfiguration: () => void;
  onLogout: () => void;
}) {
  const [app, setApp] = useState<App | null>(null);
  const [apps, setApps] = useState<App[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<string>("overview");
  const [focusManagedIssuer, setFocusManagedIssuer] = useState(false);
  const [mobileNavigationOpen, setMobileNavigationOpen] = useState(false);
  const [reloadKey, setReloadKey] = useState(0);
  const navigationButtonRef = useRef<HTMLButtonElement>(null);
  const navigationCloseRef = useRef<HTMLButtonElement>(null);
  const navigationDrawerRef = useRef<HTMLElement>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const [currentApp, appList] = await Promise.all([
        api<App>(`/admin/apps/${encodeURIComponent(appId)}`),
        api<{ items: App[] }>("/admin/apps"),
      ]);
      setApp(currentApp);
      setApps(appList.items);
      onAppChange?.(currentApp);
    } catch (caught) {
      setError(formatErrorSafe(caught));
    }
  }, [appId, onAppChange]);

  useEffect(() => {
    void load();
  }, [load, reloadKey]);

  useEffect(() => {
    if (!mobileNavigationOpen) return;
    document.body.classList.add("drawer-open");
    const focusTimer = window.setTimeout(() => navigationCloseRef.current?.focus(), 200);
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        closeMobileNavigation();
        return;
      }
      if (event.key !== "Tab" || !navigationDrawerRef.current) return;
      const focusable = Array.from(navigationDrawerRef.current.querySelectorAll<HTMLElement>(
        "button:not([disabled]), select:not([disabled]), [href], [tabindex]:not([tabindex='-1'])",
      ));
      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (!first || !last) return;
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.clearTimeout(focusTimer);
      document.body.classList.remove("drawer-open");
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [mobileNavigationOpen]);

  useEffect(() => {
    setMobileNavigationOpen(false);
  }, [appId]);

  useEffect(() => {
    document.title = app?.appId === appId ? `UniCAS | ${app.displayName}` : "UniCAS";
    return () => {
      document.title = "UniCAS";
    };
  }, [app, appId]);

  useEffect(() => () => onAppChange?.(null), [onAppChange]);

  const reload = () => setReloadKey((key) => key + 1);
  const activeTab = TABS.find((item) => item.id === tab) ?? TABS[0];
  const activeGuide = TAB_GUIDES[activeTab.id];

  function closeMobileNavigation() {
    setMobileNavigationOpen(false);
    requestAnimationFrame(() => navigationButtonRef.current?.focus());
  }

  function selectTab(id: string) {
    setFocusManagedIssuer(false);
    setTab(id);
    if (mobileNavigationOpen) closeMobileNavigation();
  }

  if (error) {
    return (
      <section className="page">
        <PageHeading title="App" />
        <div className="flex items-center gap-2 text-sm text-destructive">
          <CircleAlert className="h-4 w-4" />
          <span>{error}</span>
        </div>
      </section>
    );
  }
  if (!app || !apps) {
    return (
      <section className="page">
        <PageHeading title="App" />
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <LoaderCircle className="h-4 w-4 animate-spin" />
          <span>Loading…</span>
        </div>
      </section>
    );
  }

  return (
    <section className="page">
      <PageHeading title={app.displayName} />
      <button
        ref={navigationButtonRef}
        type="button"
        className="mobile-nav-trigger"
        aria-controls="stack-navigation"
        aria-expanded={mobileNavigationOpen}
        aria-label={`Open navigation, current section ${activeTab.label}`}
        title={`Navigation: ${activeTab.label}`}
        onClick={() => setMobileNavigationOpen(true)}
      >
        <Menu size={19} />
      </button>
      <div className="stack-layout">
        {mobileNavigationOpen ? (
          <div
            className="drawer-overlay"
            aria-hidden="true"
            onClick={closeMobileNavigation}
          />
        ) : null}
        <aside
          ref={navigationDrawerRef}
          id="stack-navigation"
          className={`stack-sidebar${mobileNavigationOpen ? " stack-sidebar-open" : ""}`}
          role={mobileNavigationOpen ? "dialog" : undefined}
          aria-modal={mobileNavigationOpen ? true : undefined}
          aria-label="App management navigation"
        >
          <div className="drawer-header">
            <a className="drawer-brand" href="#/">
              <span className="brand-mark">U</span>
              <span>UniCAS Admin</span>
            </a>
            <button
              ref={navigationCloseRef}
              type="button"
              className="drawer-close"
              aria-label="Close navigation"
              onClick={closeMobileNavigation}
            >
              <X size={17} />
            </button>
          </div>
          <div className="stack-switcher">
            <label htmlFor="stack-switcher">App</label>
            <select
              id="stack-switcher"
              value={appId}
              onChange={(event) => {
                navigate(`/apps/${encodeURIComponent(event.target.value)}`);
                if (mobileNavigationOpen) closeMobileNavigation();
              }}
            >
              {apps.map((option) => (
                <option key={option.appId} value={option.appId}>{option.displayName}</option>
              ))}
            </select>
          </div>
          <nav className="tabs tabs-vertical" role="tablist" aria-orientation="vertical">
            {TABS.map((tabItem) => (
              <button
                key={tabItem.id}
                type="button"
                role="tab"
                aria-selected={tabItem.id === tab}
                className={`tab tab-vertical${tabItem.id === tab ? " tab-active" : ""}`}
                onClick={() => selectTab(tabItem.id)}
              >
                {tabItem.icon ? <span className="tab-icon" aria-hidden="true">{tabItem.icon}</span> : null}
                {tabItem.label}
              </button>
            ))}
          </nav>
          <div className="drawer-footer">
            <button
              type="button"
              className="drawer-action"
              onClick={() => {
                closeMobileNavigation();
                onOpenMcpConfiguration();
              }}
            >
              <Cable size={15} />
              <span>Connect AI tools</span>
            </button>
            <button type="button" className="drawer-signout" onClick={onLogout}>
              <LogOut size={15} />
              <span>Sign out</span>
            </button>
          </div>
        </aside>
        <section className="stack-content" aria-hidden={mobileNavigationOpen ? true : undefined}>
          {tab !== "playground" ? (
            <aside className="concept-guide" aria-labelledby={`concept-${activeGuide.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>
              <BookOpenText className="concept-guide-icon" size={18} aria-hidden="true" />
              <div className="concept-guide-content">
                <p className="concept-guide-label">About this page</p>
                <h2 id={`concept-${activeGuide.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>{activeGuide.title}</h2>
                <p className="concept-guide-summary">{activeGuide.summary}</p>
                <dl className="concept-list">
                  {activeGuide.concepts.map((concept) => (
                    <div key={concept.term}>
                      <dt>{concept.term}</dt>
                      <dd>{concept.detail}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            </aside>
          ) : null}
          {tab === "overview" ? (
            <>
              <AppOverviewView app={app} onChanged={reload} />
              <IssuerView appId={appId} focusManagedIssuer={focusManagedIssuer} />
              <UsageView appId={appId} />
            </>
          ) : null}
          {tab === "members" ? <MembersView appId={appId} appRevision={app.revision} onChanged={reload} /> : null}
          {tab === "playground" ? <PlaygroundView appId={appId} onOpenManagedIssuer={() => {
            selectTab("overview");
            setFocusManagedIssuer(true);
          }} /> : null}
          {tab === "change-log" ? <ControlAuditView appId={appId} /> : null}
        </section>
      </div>
    </section>
  );
}
