import type { D1Database } from "@cloudflare/workers-types";

const CONTROL_TABLES = [
  "CREATE TABLE IF NOT EXISTS cas_accounts (account_id TEXT PRIMARY KEY CHECK(length(account_id) = 27 AND substr(account_id, 1, 5) = 'acct_'), blocked_at INTEGER CHECK(blocked_at IS NULL OR blocked_at >= 0), credential_version INTEGER NOT NULL DEFAULT 1 CHECK(credential_version >= 1), primary_verified_email TEXT, email_verification_source TEXT CHECK(email_verification_source IS NULL OR email_verification_source IN ('google-oidc','github-emails-api','unicas-email-challenge')), email_verified_at INTEGER CHECK(email_verified_at IS NULL OR email_verified_at >= 0), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, CHECK((primary_verified_email IS NULL AND email_verification_source IS NULL AND email_verified_at IS NULL) OR (primary_verified_email IS NOT NULL AND email_verification_source IS NOT NULL AND email_verified_at IS NOT NULL)))",
  "CREATE TABLE IF NOT EXISTS cas_account_profiles (account_id TEXT PRIMARY KEY, display_name TEXT, avatar_url TEXT, display_name_source TEXT, avatar_source TEXT, updated_at INTEGER NOT NULL, FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_external_identities (external_identity_id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider TEXT NOT NULL CHECK(provider IN ('google','microsoft','github')), issuer TEXT NOT NULL, subject TEXT NOT NULL, linked_at INTEGER NOT NULL, last_authenticated_at INTEGER, unlinked_at INTEGER, account_hint TEXT, display_name TEXT, avatar_url TEXT, FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_account_platform_authorities (account_id TEXT NOT NULL, authority TEXT NOT NULL CHECK(authority IN ('platform.admin','apps.create')), granted_at INTEGER NOT NULL, PRIMARY KEY(account_id, authority), FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_account_aliases (source_account_id TEXT PRIMARY KEY, canonical_account_id TEXT NOT NULL, created_at INTEGER NOT NULL, reason TEXT NOT NULL, CHECK(source_account_id <> canonical_account_id), FOREIGN KEY(source_account_id) REFERENCES cas_accounts(account_id), FOREIGN KEY(canonical_account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_platform_audit_events (event_id TEXT PRIMARY KEY, actor_account_id TEXT NOT NULL, actor_external_identity_id TEXT NOT NULL, target_account_id TEXT, target_invitation_id TEXT, action TEXT NOT NULL, result TEXT NOT NULL CHECK(result IN ('succeeded','denied')), request_id TEXT, created_at INTEGER NOT NULL, details_json TEXT NOT NULL DEFAULT '{}', FOREIGN KEY(actor_account_id) REFERENCES cas_accounts(account_id), FOREIGN KEY(actor_external_identity_id) REFERENCES cas_external_identities(external_identity_id), FOREIGN KEY(target_account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_platform_invitations (invitation_id TEXT PRIMARY KEY, email_constraint TEXT NOT NULL, platform_admin INTEGER NOT NULL DEFAULT 0 CHECK(platform_admin IN (0,1)), apps_create INTEGER NOT NULL DEFAULT 0 CHECK(apps_create IN (0,1)), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','expired','revoked')), token_hash TEXT NOT NULL UNIQUE, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, created_by_account_id TEXT NOT NULL, created_by_external_identity_id TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(created_by_account_id) REFERENCES cas_accounts(account_id), FOREIGN KEY(created_by_external_identity_id) REFERENCES cas_external_identities(external_identity_id))",
  "CREATE TABLE IF NOT EXISTS cas_platform_invitation_idempotency (actor_account_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, payload_hash TEXT NOT NULL, invitation_id TEXT NOT NULL, sealed_token TEXT NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY(actor_account_id, idempotency_key), FOREIGN KEY(actor_account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_apps (app_id TEXT PRIMARY KEY, display_name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended')), created_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1)",
  "CREATE TABLE IF NOT EXISTS cas_app_members (app_id TEXT NOT NULL, account_id TEXT NOT NULL, joined_at INTEGER NOT NULL, PRIMARY KEY(app_id, account_id), FOREIGN KEY(app_id) REFERENCES cas_apps(app_id), FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_app_member_invitations (invitation_id TEXT PRIMARY KEY, app_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','expired','revoked')), email_constraint TEXT, token_hash TEXT NOT NULL UNIQUE, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(app_id) REFERENCES cas_apps(app_id))",
  "CREATE TABLE IF NOT EXISTS cas_app_oauth_issuers (app_id TEXT PRIMARY KEY, mode TEXT NOT NULL DEFAULT 'external', issuer TEXT NOT NULL, audience TEXT NOT NULL, metadata_url TEXT NOT NULL, metadata_type TEXT NOT NULL CHECK(metadata_type IN ('oauth','oidc')), authorization_endpoint TEXT NOT NULL, token_endpoint TEXT NOT NULL, jwks_uri TEXT NOT NULL, registration_endpoint TEXT, scopes_supported TEXT NOT NULL DEFAULT '[]', code_challenge_methods_supported TEXT NOT NULL DEFAULT '[]', status TEXT NOT NULL CHECK(status IN ('pending','active','stale','incompatible','disabled')), verified_at INTEGER, last_refresh_at INTEGER, last_refresh_error TEXT, jwks_digest TEXT NOT NULL, capability_max_lifetime_seconds INTEGER NOT NULL DEFAULT 28800 CHECK(capability_max_lifetime_seconds BETWEEN 60 AND 604800), revision INTEGER NOT NULL DEFAULT 1)",
  "CREATE TABLE IF NOT EXISTS cas_app_managed_issuers (app_id TEXT PRIMARY KEY, issuer TEXT NOT NULL UNIQUE, audience TEXT NOT NULL, metadata_url TEXT NOT NULL, authorization_endpoint TEXT NOT NULL, token_endpoint TEXT NOT NULL, jwks_uri TEXT NOT NULL, scopes_supported TEXT NOT NULL DEFAULT '[]', code_challenge_methods_supported TEXT NOT NULL DEFAULT '[]', status TEXT NOT NULL CHECK(status IN ('active','disabled')), verified_at INTEGER NOT NULL, jwks_digest TEXT NOT NULL, capability_max_lifetime_seconds INTEGER NOT NULL DEFAULT 3600 CHECK(capability_max_lifetime_seconds BETWEEN 60 AND 604800), revision INTEGER NOT NULL DEFAULT 1)",
  "CREATE TABLE IF NOT EXISTS cas_oauth_issuer_inspections (inspection_id TEXT PRIMARY KEY, app_id TEXT NOT NULL, issuer TEXT NOT NULL, audience TEXT NOT NULL, metadata_url TEXT NOT NULL, metadata_type TEXT NOT NULL CHECK(metadata_type IN ('oauth','oidc')), authorization_endpoint TEXT NOT NULL, token_endpoint TEXT NOT NULL, jwks_uri TEXT NOT NULL, registration_endpoint TEXT, scopes_supported TEXT NOT NULL DEFAULT '[]', code_challenge_methods_supported TEXT NOT NULL DEFAULT '[]', metadata_digest TEXT NOT NULL, jwks_digest TEXT NOT NULL, challenge_hash TEXT NOT NULL, capability_max_lifetime_seconds INTEGER NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER, revision INTEGER NOT NULL DEFAULT 1)",
  "CREATE TABLE IF NOT EXISTS cas_oauth_issuer_inspection_keys (inspection_id TEXT NOT NULL, kid TEXT NOT NULL, algorithm TEXT NOT NULL, public_jwk TEXT NOT NULL, PRIMARY KEY(inspection_id, kid), FOREIGN KEY(inspection_id) REFERENCES cas_oauth_issuer_inspections(inspection_id))",
  "CREATE TABLE IF NOT EXISTS cas_control_audit_events (event_id TEXT PRIMARY KEY, app_id TEXT, action TEXT NOT NULL, target TEXT NOT NULL, request_id TEXT, trace_id TEXT, caller_channel TEXT, oauth_client_handle TEXT, tool_name TEXT, created_at INTEGER NOT NULL, original_account_id TEXT NOT NULL, external_identity_id TEXT NOT NULL, target_account_id TEXT, FOREIGN KEY(original_account_id) REFERENCES cas_accounts(account_id), FOREIGN KEY(external_identity_id) REFERENCES cas_external_identities(external_identity_id), FOREIGN KEY(target_account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_account_app_idempotency (account_id TEXT NOT NULL, method TEXT NOT NULL, canonical_route TEXT NOT NULL, idempotency_key TEXT NOT NULL, payload_hash TEXT NOT NULL, response_json TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY(account_id, method, canonical_route, idempotency_key), FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_account_app_invitation_idempotency (account_id TEXT NOT NULL, app_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, payload_hash TEXT NOT NULL, response_json TEXT NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, PRIMARY KEY(account_id, app_id, idempotency_key), FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id))",
  "CREATE TABLE IF NOT EXISTS cas_admin_sessions (session_id TEXT PRIMARY KEY, encrypted_payload TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, last_seen_at INTEGER NOT NULL, account_id TEXT, external_identity_id TEXT, credential_version INTEGER, FOREIGN KEY(account_id) REFERENCES cas_accounts(account_id), FOREIGN KEY(external_identity_id) REFERENCES cas_external_identities(external_identity_id))",
  "CREATE TABLE IF NOT EXISTS cas_email_challenges (challenge_id TEXT PRIMARY KEY, invitation_kind TEXT NOT NULL CHECK(invitation_kind IN ('app','platform')), invitation_id TEXT NOT NULL, invitation_token_hash TEXT NOT NULL, identity_issuer TEXT NOT NULL, subject TEXT NOT NULL, authentication_event_id TEXT NOT NULL, normalized_email TEXT NOT NULL, code_hash TEXT NOT NULL CHECK(length(code_hash) = 64), expires_at INTEGER NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count >= 0), max_attempts INTEGER NOT NULL CHECK(max_attempts > 0), send_count INTEGER NOT NULL DEFAULT 1 CHECK(send_count > 0), last_sent_at INTEGER NOT NULL, verified_at INTEGER, consumed_at INTEGER, invalidated_at INTEGER, created_at INTEGER NOT NULL, CHECK(verified_at IS NULL OR verified_at >= created_at), CHECK(consumed_at IS NULL OR (verified_at IS NOT NULL AND consumed_at >= verified_at)), CHECK(invalidated_at IS NULL OR invalidated_at >= created_at))",
  "CREATE TABLE IF NOT EXISTS cas_control_meta (key TEXT PRIMARY KEY, value INTEGER NOT NULL)",
];

const CONTROL_INDEXES = [
  "CREATE UNIQUE INDEX IF NOT EXISTS cas_external_identities_active_key ON cas_external_identities(issuer, subject) WHERE unlinked_at IS NULL",
  "CREATE INDEX IF NOT EXISTS cas_external_identities_by_account ON cas_external_identities(account_id, unlinked_at, last_authenticated_at)",
  "CREATE INDEX IF NOT EXISTS cas_account_authorities_by_authority ON cas_account_platform_authorities(authority, account_id)",
  "CREATE INDEX IF NOT EXISTS cas_account_aliases_by_canonical ON cas_account_aliases(canonical_account_id, source_account_id)",
  "CREATE INDEX IF NOT EXISTS cas_app_members_by_account ON cas_app_members(account_id, app_id)",
  "CREATE INDEX IF NOT EXISTS cas_control_audit_by_account ON cas_control_audit_events(original_account_id, created_at, event_id)",
  "CREATE INDEX IF NOT EXISTS cas_control_audit_by_target_account ON cas_control_audit_events(target_account_id, created_at, event_id) WHERE target_account_id IS NOT NULL",
  "CREATE INDEX IF NOT EXISTS cas_platform_audit_by_actor_account ON cas_platform_audit_events(actor_account_id, created_at, event_id)",
  "CREATE INDEX IF NOT EXISTS cas_platform_audit_by_target_account ON cas_platform_audit_events(target_account_id, created_at, event_id) WHERE target_account_id IS NOT NULL",
  "CREATE INDEX IF NOT EXISTS cas_admin_sessions_by_account ON cas_admin_sessions(account_id, credential_version, expires_at) WHERE account_id IS NOT NULL",
  "CREATE INDEX IF NOT EXISTS cas_invitations_by_token_hash ON cas_app_member_invitations(token_hash)",
  "CREATE INDEX IF NOT EXISTS cas_platform_invitations_by_email ON cas_platform_invitations(email_constraint, invitation_id)",
  "CREATE INDEX IF NOT EXISTS cas_platform_invitation_idempotency_by_expiry ON cas_platform_invitation_idempotency(expires_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS cas_oauth_issuer_by_issuer ON cas_app_oauth_issuers(issuer)",
  "CREATE INDEX IF NOT EXISTS cas_oauth_issuers_by_status ON cas_app_oauth_issuers(status, app_id)",
  "CREATE INDEX IF NOT EXISTS cas_managed_issuers_by_status ON cas_app_managed_issuers(status, app_id)",
  "CREATE INDEX IF NOT EXISTS cas_oauth_inspections_by_app ON cas_oauth_issuer_inspections(app_id, created_at)",
  "CREATE INDEX IF NOT EXISTS cas_oauth_inspections_by_expiry ON cas_oauth_issuer_inspections(expires_at)",
  "CREATE INDEX IF NOT EXISTS cas_control_audit_by_app ON cas_control_audit_events(app_id, created_at, event_id)",
  "CREATE INDEX IF NOT EXISTS cas_account_app_idempotency_by_expiry ON cas_account_app_idempotency(expires_at)",
  "CREATE INDEX IF NOT EXISTS cas_account_app_invitation_idempotency_by_expiry ON cas_account_app_invitation_idempotency(expires_at)",
  "CREATE INDEX IF NOT EXISTS cas_admin_sessions_by_expiry ON cas_admin_sessions(expires_at)",
  "CREATE INDEX IF NOT EXISTS cas_email_challenges_by_expiry ON cas_email_challenges(expires_at, challenge_id)",
  "CREATE INDEX IF NOT EXISTS cas_email_challenges_by_invitation ON cas_email_challenges(invitation_kind, invitation_id, consumed_at)",
];

export const CONTROL_SCHEMA_MIGRATIONS = [...CONTROL_TABLES, ...CONTROL_INDEXES];

export async function migrateControlSchema(db: D1Database): Promise<void> {
  for (const sql of CONTROL_SCHEMA_MIGRATIONS) await db.exec(sql);
}